### ISSUE TITLE
setOptionsFromProps creates wrong param order

### ISSUE THREAD

**Issue by K-Leon** [skratchdot/react-bootstrap-daterangepicker#82] opened 2016-07-26 19:56 UTC
I just noticed a really problematic part in setOptionsFromProps. The function assumes that Object.keys delivers a specific order - it won't deliver this order reliable.

This results in issues if startDate is set after endDate. ( endDate get's reset )

https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/eedc6c52370d53da6d0b885e4d6410989eec9aa5/lib/index.js#L47

If there's interest i'll send a bugfix ( moving endDate out of loop for now ).

**Comment by y3wegy** [comment] 2018-04-11 07:40
i am same issue , this component can't set end date from parent ,end date will reset to TODAY .  i found the root cause is props order : end date before start date. So how to fix? custom code ?

**Comment by skratchdot** [comment] 2018-04-11 18:14
Thank you @y3wegy / @K-Leon -  Seems like we need custom `sort()` here, so that start date happens before end date:
https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/eedc6c52370d53da6d0b885e4d6410989eec9aa5/lib/index.js#L44

I might be able to look into this after work today, but PR's are welcomed.  Now that this repo has unit tests (and storybook), we should add a simple reproducible test case, then we can fix it (and make sure it doesn't happen again).

**Comment by skratchdot** [comment] 2018-04-11 23:35
It looks like @adewitt76 submitted a fix for this in #139 , but I never saw that.  Someone can try to submit a similar PR.

**Comment by skratchdot** [comment] 2020-07-26 13:18
closing this due to inactivity. please re-open if this is still an issue in v6.0.0 or greater

**Closed by skratchdot** 2020-07-26 13:18 UTC
