### ISSUE TITLE
Cannot set property 'daterangepicker' of undefined

### ISSUE THREAD

**Issue by aauberg** [skratchdot/react-bootstrap-daterangepicker#43] opened 2015-10-31 16:53 UTC
I am using webpack to bundle my app. I get this error right after webpack says the bundle is VALID.

```
/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:1483
    $.fn.daterangepicker = function(options, callback) {
                         ^

TypeError: Cannot set property 'daterangepicker' of undefined
    at /home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:1483:26
    at cb.parentEl (/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:28:5)
    at Object.<anonymous> (/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:35:2)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/aaron/Repos/smart-spray-portal/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I am not certain where to look for an answer to this issue. I don't believe that webpack is the problem, since it bundles fine. I am looking at my babel setup to see if there is anything missing there. Any suggestions from anyone?

**Comment by aauberg** [comment] 2015-10-31 17:04
The issues is resolved by using version 1.0.2 instead of 1.0.3. Does anyone else have this issues with 1.0.3?

**Comment by skratchdot** [comment] 2015-10-31 17:55
I published v1.0.3 because someone was seeing this error.  I've been debugging the 1.0.3 version- it's definitely something with webpack and the way packages are bundled, but I haven't had much luck debugging the issue.  I've been adding breakpoints in my debugger that I *think* should be reached, but they aren't.  I've tried debugging in Chrome/Firefox/Firebug.  Not sure if the code's really not being reached, or if it's an issue w/ sourcemaps and webpack.  Anyways, I'm gonna keep trying.  Think I should publish 1.0.4 which is a copy of 1.0.2 or keep the current version 1.0.3?

**Comment by aauberg** [comment] 2015-10-31 18:00
Maybe branch what you are bugcrushing and get 1.0.2 up at the head of the main branch again. You said someone else was seeing this error on 1.0.2?

**Comment by skratchdot** [comment] 2015-10-31 19:54
Yeah- I made 1.0.3 trying to fix #41.  I couldn't reproduce though.  But I now know it's something w/ webpack.  I've started using webpack in other projects, but never tested w/ this one until checking out the project @mateuszpalyz posted in #42.

**Comment by Aldredcz** [comment] 2015-11-02 21:29
@skratchdot I got the same error - 1.0.2 working, 1.0.3 error. Using webpack. If you need any additional info, let me know.

**Comment by skratchdot** [comment] 2015-11-02 22:36
Ok. I re-published v1.0.2 as v1.0.4 until I find a fix for v1.0.3.

**Comment by ThrowsException** [comment] 2016-07-08 14:23
What version of npm are you using? I noticed I ran into this issue with npm2.15 but not when I used npm3.9.x. It looks like something with the dependencies being flattened in npm3 makes webpack work with this module as its written where the nested dependencies using npm2 break webpack when it bundles it.

**Comment by skratchdot** [comment] 2016-07-08 14:32
@ThrowsException - Thanks for the info!  I've been using npm3 (basically since it came out)- so that is probably the issue.  There are some other things to try/watch out for like using webpack externals for jquery, as well as looking into using jQuery.noConflict.  I just haven't had the time to troubleshoot this because I'm no longer using the library (and it works/worked for my needs).  I'd glady accept any PR's though!

Thanks again for adding to the discussion.  Hopefully moving to npm3 fixes the issue for people!

**Comment by ThrowsException** [comment] 2016-07-08 15:32
@skratchdot Yea I caught this because our CI is a bit behind on npm so locally we ran fine but once CI picked it up the build failed at runtime because of this issue. I've also seen this issue linked in stackoverflow. Seems to be an issue with the UMD wrapper and some combination of webpack/babel 

http://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined

**Comment by guitarama** [comment] 2017-05-22 20:29
I'm using webpack npm3 and we're falling into the "AMD" part of the module setup.  I created a PR to the source lib: https://github.com/dangrossman/bootstrap-daterangepicker/pull/1482

**Comment by wzup** [comment] 2017-10-03 08:38
So what error is this? I experience it too. How to fix?

![datepicker - google chrome 2017-10-03 16 36 36](https://user-images.githubusercontent.com/3880497/31116554-1e121296-a859-11e7-8289-796fcf3839db.png)

![datepicker - google chrome 2017-10-03 16 37 58](https://user-images.githubusercontent.com/3880497/31116610-4c3769aa-a859-11e7-934e-edf399f1a705.png)

**Comment by skratchdot** [comment] 2020-07-26 13:15
closing this due to inactivity. please re-open if this is still an issue in v6.0.0 or greater

**Closed by skratchdot** 2020-07-26 13:15 UTC
